### ISSUE TITLE
JSRELOAD don't work

### ISSUE THREAD

**Issue by h0x91b** [h0x91b/redis-v8#1]
After last V8 update JSRELOAD is broken

**Comment by m1sta** [comment]
Consider having javascript functions loaded from a hashset in redis instead of from the filesystem. Further to this it would be great if simple versioning could be implemented too such that a developer could write redis.jsCall(functionName,  argumentArray, versionMap, callback)

**Comment by h0x91b** [comment]
Very good idea! I will implement this, thanks a lot!

**Comment by fattenap** [comment]
Hi @m1sta, what's the reasoning behind your suggestion to load javascript functions from a hashset rather than the file system.

**Comment by h0x91b** [comment]
This can help for versioning and easy to distribute over cluster. But files better for backups.

**Comment by h0x91b** [comment]
fixed
